version: '3.4'

networks:
  dev:
    driver: bridge
  
services:
  communication-control:
    image: docker.io/danylohoncahrov/communication-control
    depends_on:
      - "redis"
    ports:
      - "8080:8080"
    environment:
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - dev

  hive-mind:
    image: docker.io/danylohoncahrov/hive-mind
    depends_on:
      - "communication-control"
    ports:
      - "5149:5149"
    environment:
      - CommunicationConfiguration__CommunicationControlIP=communication-control
      - ASPNETCORE_URLS=http://+:5149
    networks:
      - dev
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dev
  
  map-client:
    image: docker.io/danylohoncahrov/map-client
    depends_on:
      - "communication-control"
    ports:
      - "8081:80"
    networks:
      - dev